# fly.toml app configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'glowform-rjuroq'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2 # Start with 2 machines always running
  max_machines_running = 5 # Allow up to 5 machines for scaling
  processes = ['app']

[[vm]]
  memory = '2gb' # Increase memory to 2GB
  cpu_kind = 'shared' # Shared CPUs for moderate scaling
  cpus = 2 # Allocate 2 CPUs for better performance
  memory_mb = 2048 # Match memory in MB
